[build]
  publish = "src"  # Directory where Netlify will look for files to deploy
  command = "npx tailwindcss -i ./src/input.css -o ./src/output.css --minify"  # Tailwind build command

[build.environment]
  NODE_VERSION = "18"  # Ensure Node.js version compatibility

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
